-- Generated from src/database/postgresSchema.js. Apply as cf_monitor_migrator only.
-- psql -X -U cf_monitor_migrator -d cf_server_monitor -f scripts/postgres-schema.sql
\set ON_ERROR_STOP on
SET search_path = cf_server_monitor, pg_catalog;

CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT);

CREATE TABLE IF NOT EXISTS servers ("id" TEXT PRIMARY KEY,
"name" TEXT,
"server_group" TEXT DEFAULT 'Default',
"region" TEXT DEFAULT '',
"tags" TEXT DEFAULT '',
"note" TEXT DEFAULT '',
"price" TEXT DEFAULT '',
"billing_cycle" TEXT DEFAULT 'month',
"auto_renewal" TEXT DEFAULT '0',
"currency" TEXT DEFAULT '¥',
"expire_date" TEXT DEFAULT '',
"traffic_limit" TEXT DEFAULT '',
"traffic_calc_type" TEXT DEFAULT 'total',
"interface" TEXT DEFAULT '',
"reset_day" INTEGER DEFAULT 1,
"collect_interval" INTEGER DEFAULT 0,
"report_interval" INTEGER DEFAULT 60,
"wss_report_interval" INTEGER DEFAULT 2,
"connection_mode" TEXT DEFAULT 'auto',
"ping_mode" TEXT DEFAULT 'tcp',
"auto_update" TEXT DEFAULT '0',
"custom_ct" TEXT DEFAULT '',
"custom_cu" TEXT DEFAULT '',
"custom_cm" TEXT DEFAULT '',
"custom_bd" TEXT DEFAULT '',
"node_1" TEXT DEFAULT '',
"node_2" TEXT DEFAULT '',
"node_3" TEXT DEFAULT '',
"node_4" TEXT DEFAULT '',
"rx_correction" DOUBLE PRECISION DEFAULT NULL,
"tx_correction" DOUBLE PRECISION DEFAULT NULL,
"offline_notify_disabled" TEXT DEFAULT '0',
"is_hidden" TEXT DEFAULT '0',
"sort_order" INTEGER DEFAULT 0,
"history_partition_id" INTEGER NOT NULL CHECK (history_partition_id BETWEEN 1 AND 900),
"timestamp" BIGINT DEFAULT 0);

CREATE UNIQUE INDEX IF NOT EXISTS servers_history_partition_unique ON servers (history_partition_id);

CREATE TABLE IF NOT EXISTS metrics_history ("id" BIGINT PRIMARY KEY CHECK (id BETWEEN 0 AND 9007199254740991),
"server_id" TEXT NOT NULL,
"timestamp" BIGINT NOT NULL DEFAULT 0,
"agent_version" TEXT DEFAULT '',
"cpu" DOUBLE PRECISION DEFAULT 0,
"load_avg" TEXT DEFAULT '0',
"net_in_speed" DOUBLE PRECISION DEFAULT 0,
"net_out_speed" DOUBLE PRECISION DEFAULT 0,
"net_rx" DOUBLE PRECISION DEFAULT 0,
"net_tx" DOUBLE PRECISION DEFAULT 0,
"processes" BIGINT DEFAULT 0,
"tcp_conn" BIGINT DEFAULT 0,
"udp_conn" BIGINT DEFAULT 0,
"ping_ct" BIGINT DEFAULT NULL,
"ping_cu" BIGINT DEFAULT NULL,
"ping_cm" BIGINT DEFAULT NULL,
"ping_bd" BIGINT DEFAULT NULL,
"ping_node_1" BIGINT DEFAULT NULL,
"ping_node_2" BIGINT DEFAULT NULL,
"ping_node_3" BIGINT DEFAULT NULL,
"ping_node_4" BIGINT DEFAULT NULL,
"loss_ct" BIGINT DEFAULT NULL,
"loss_cu" BIGINT DEFAULT NULL,
"loss_cm" BIGINT DEFAULT NULL,
"loss_bd" BIGINT DEFAULT NULL,
"loss_node_1" BIGINT DEFAULT NULL,
"loss_node_2" BIGINT DEFAULT NULL,
"loss_node_3" BIGINT DEFAULT NULL,
"loss_node_4" BIGINT DEFAULT NULL,
"ram_total" DOUBLE PRECISION DEFAULT 0,
"ram_used" DOUBLE PRECISION DEFAULT 0,
"swap_total" DOUBLE PRECISION DEFAULT 0,
"swap_used" DOUBLE PRECISION DEFAULT 0,
"disk_total" DOUBLE PRECISION DEFAULT 0,
"disk_used" DOUBLE PRECISION DEFAULT 0,
"disk_read_bps" DOUBLE PRECISION,
"disk_write_bps" DOUBLE PRECISION,
"disk_read_iops" DOUBLE PRECISION,
"disk_write_iops" DOUBLE PRECISION,
"disk_await_ms" DOUBLE PRECISION,
"disk_util" DOUBLE PRECISION,
"cpu_cores" BIGINT DEFAULT 0,
"cpu_info" TEXT DEFAULT '',
"gpu_info" TEXT DEFAULT '',
"arch" TEXT DEFAULT '',
"os" TEXT DEFAULT '',
"kernel_version" TEXT DEFAULT '',
"region" TEXT DEFAULT '',
"ip_v4" TEXT DEFAULT '0',
"ip_v6" TEXT DEFAULT '0',
"boot_time" TEXT DEFAULT '',
"net_rx_monthly" DOUBLE PRECISION DEFAULT 0,
"net_tx_monthly" DOUBLE PRECISION DEFAULT 0);

CREATE INDEX IF NOT EXISTS metrics_history_server_time ON metrics_history (server_id, timestamp);

CREATE INDEX IF NOT EXISTS metrics_history_retention_time ON metrics_history (timestamp);

CREATE TABLE IF NOT EXISTS metrics_history_old ("id" BIGINT PRIMARY KEY CHECK (id BETWEEN 0 AND 9007199254740991),
"server_id" TEXT NOT NULL,
"timestamp" BIGINT NOT NULL DEFAULT 0,
"agent_version" TEXT DEFAULT '',
"cpu" DOUBLE PRECISION DEFAULT 0,
"load_avg" TEXT DEFAULT '0',
"net_in_speed" DOUBLE PRECISION DEFAULT 0,
"net_out_speed" DOUBLE PRECISION DEFAULT 0,
"net_rx" DOUBLE PRECISION DEFAULT 0,
"net_tx" DOUBLE PRECISION DEFAULT 0,
"processes" BIGINT DEFAULT 0,
"tcp_conn" BIGINT DEFAULT 0,
"udp_conn" BIGINT DEFAULT 0,
"ping_ct" BIGINT DEFAULT NULL,
"ping_cu" BIGINT DEFAULT NULL,
"ping_cm" BIGINT DEFAULT NULL,
"ping_bd" BIGINT DEFAULT NULL,
"ping_node_1" BIGINT DEFAULT NULL,
"ping_node_2" BIGINT DEFAULT NULL,
"ping_node_3" BIGINT DEFAULT NULL,
"ping_node_4" BIGINT DEFAULT NULL,
"loss_ct" BIGINT DEFAULT NULL,
"loss_cu" BIGINT DEFAULT NULL,
"loss_cm" BIGINT DEFAULT NULL,
"loss_bd" BIGINT DEFAULT NULL,
"loss_node_1" BIGINT DEFAULT NULL,
"loss_node_2" BIGINT DEFAULT NULL,
"loss_node_3" BIGINT DEFAULT NULL,
"loss_node_4" BIGINT DEFAULT NULL,
"ram_total" DOUBLE PRECISION DEFAULT 0,
"ram_used" DOUBLE PRECISION DEFAULT 0,
"swap_total" DOUBLE PRECISION DEFAULT 0,
"swap_used" DOUBLE PRECISION DEFAULT 0,
"disk_total" DOUBLE PRECISION DEFAULT 0,
"disk_used" DOUBLE PRECISION DEFAULT 0,
"disk_read_bps" DOUBLE PRECISION,
"disk_write_bps" DOUBLE PRECISION,
"disk_read_iops" DOUBLE PRECISION,
"disk_write_iops" DOUBLE PRECISION,
"disk_await_ms" DOUBLE PRECISION,
"disk_util" DOUBLE PRECISION,
"cpu_cores" BIGINT DEFAULT 0,
"cpu_info" TEXT DEFAULT '',
"gpu_info" TEXT DEFAULT '',
"arch" TEXT DEFAULT '',
"os" TEXT DEFAULT '',
"kernel_version" TEXT DEFAULT '',
"region" TEXT DEFAULT '',
"ip_v4" TEXT DEFAULT '0',
"ip_v6" TEXT DEFAULT '0',
"boot_time" TEXT DEFAULT '',
"net_rx_monthly" DOUBLE PRECISION DEFAULT 0,
"net_tx_monthly" DOUBLE PRECISION DEFAULT 0);

CREATE INDEX IF NOT EXISTS metrics_history_old_server_time ON metrics_history_old (server_id, timestamp);

CREATE INDEX IF NOT EXISTS metrics_history_old_retention_time ON metrics_history_old (timestamp);
